### ISSUE TITLE
Does it support SwiftUI?

### ISSUE THREAD

**Issue by pradeepb28** [jordanbaird/SwiftKeys#6]
Hello I was wondering if it supports SwiftUI?
If so, an example of how to use it would be great :) 

Thank you

**Comment by jordanbaird** [comment]
Manual hotkey registering should work just fine. At the moment, the key recorder element isn't natively supported, but you should be able to wrap it in a custom SwiftUI view using the NSViewRepresentable protocol. [Here's an article](https://www.swiftbysundell.com/tips/inline-wrapping-of-uikit-or-appkit-views-within-swiftui/) on how you can go about doing it.

UPDATE: SwiftUI support is now built in

**Comment by jordanbaird** [comment]
https://github.com/jordanbaird/SwiftKeys/releases/tag/0.0.9
